### ISSUE TITLE
No demos only json file

### ISSUE THREAD

**Issue by penalte** [CrazyHackGUT/sm-autodemo#13]
Hello no erros in logs but i dont have demos files only json.

What could it be?

**Comment by West14** [comment]
https://github.com/CrazyHackGUT/sm-autodemo/blob/e16dfed8219e1d10219b562f71f370d75a49f19c/scripting/AutoDemo.sp#L115

In order to fix this problem you should remove last slash in the demo path.
It should look like. This problem appeared after some of last CS:GO updates.
```c
  BuildPath(Path_SM, g_szBaseDemoPath, sizeof(g_szBaseDemoPath), "data/demos");
```

**Comment by penalte** [comment]
thank you

**Comment by strteamservidores** [comment]
any help? 

**[AutoDemo_FTPUpload.smx] Cannot compress file demo-28-19:22-jb_simpsons_joneboy_str.dem**

it's literally just this error in the log

**Comment by West14** [comment]
@strteamservidores, why are you posting your question in this issue?
I guess that your problem isn't related with one discussed here.

**Comment by strteamservidores** [comment]
I think the plugin can't read the demo file, because of this update too. And a did what you said to change the slash, but only json files are created.

**Comment by CrazyHackGUT** [comment]
Officially solved. https://github.com/CrazyHackGUT/sm-autodemo/commit/401e93986585504ea9446770412853c79985d785 https://github.com/CrazyHackGUT/sm-autodemo/commit/178c23433ec94da35f0fef529561b9da8d70cce7
I'm very surprised: someone used this plugin. o_O

About uploading demos - this require additional investigation and separate issue.

**Comment by CrazyHackGUT** [comment]
If issue is still exists - please, notify me. I'll reopen and try investigate.
