### ISSUE TITLE
Оптимизация внутренних структур плагина

### ISSUE THREAD

**Issue by CrazyHackGUT** [CrazyHackGUT/sm-autodemo#15]
Завожу исью чисто для себя, потому на русском. Хотел честно на английском, но лежу на стационаре, и думается плохо.

Ядро сейчас создает много вспомогательных структур во время "рекординга". Те же события - это гарантированная связка датапака и StringMap, что иногда может приводить [к неожиданным "репортам" от СМ на тему утечки памяти](https://cdn.discordapp.com/attachments/635558616979603486/878011467553722368/logs.txt). Выдернуто из Дискорда Levels Ranks Web, [сообщение в англ саппорте](https://discord.com/channels/606207851802656794/635558616979603486/878011467763429416).
Есть смысл сразу формировать JSON во время записи, т.к. эти данные впоследствии изменяться не будут, просто не сгружать на диск. Это позволит нам один раз создать несколько JSON-хендлов на событие, и тут же их закрыть, приаттачив данные к основному жсону.
Возможно, что-то еще таким образом соптимизировать. Данные игроков, возможно?

**Comment by zie-xx** [comment]
......
