### ISSUE TITLE
How to fix "sourcetvmanager.ext.2.tf2.so: undefined symbol: Warning"

### ISSUE THREAD

**Issue by gaejuck** [CrazyHackGUT/sm-autodemo#9]
I put in the latest version of the plugin and extension to my linux server. 
But **sourcetvmanager.ext.2.tf2.so** doesn't seem to work properly. 

> [24] REST in Pawn (1.2.0): Provides HTTP and JSON natives for plugins
[25] <FAILED> file "sourcetvmanager.ext.2.tf2.so": /home/ogpbot/OGP_User_Files/7/tf/addons/sourcemod/extensions/sourcetvmanager.ext.2.tf2.so: undefined symbol: Warning
[26] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[27] SMbz2 (0.0.3): Very basic extension to de/compress bz2 files

> AutoDemo_TF2.smx ([AutoDemo] Team Fortress 2): Native "DemoRec_AddEventListener" was not found
AutoDemo/Core.smx ([AutoDemo] Core): Required extension "SourceTV Manager" file("sourcetvmanager.ext") not running
AutoDemo.smx ([AutoDemo] Core): unexpected error 23 in AskPluginLoad callback
AutoDemo_FTPUpload.smx ([AutoDemo] FTP Upload): Could not find required plugin "AutoDemo"
AutoDemo_Notify.smx ([AutoDemo] Notifications): Could not find required plugin "AutoDemo"
AutoDemo_EventManager.smx ([AutoDemo] Event Manager): Could not find required plugin "AutoDemo"
AutoDemo/EventManager.smx ([AutoDemo] Event Manager): Could not find required plugin "AutoDemo"

What should I do?

**Comment by West14** [comment]
I think you should contact the extension developer for support.

**Comment by CrazyHackGUT** [comment]
Not related with plugin. Closing.
